FROM node:20-alpine

RUN apk update && apk add chromium

RUN rm -rf package-lock.json node_modules /root/.npm && npm install puppeteer-core

CMD ["node", "-e", "require('puppeteer-core').launch({headless: 'new'}).then(browser => browser.close()).then(()=> console.log('puppeteer working'))"]